### ISSUE TITLE
I/O exception (java.net.NoRouteToHostException) wenn http Schalter nicht erreichbar

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#103]
SAE 1.5.5 zeigt gar keine Geräte mehr an wenn ein Gosund Schalter (Tasmota 8.2.0) nicht erreichbar ist. Zum reproduzieren einfach einen Tasmota Schalter aus der Steckdose ziehen und testen.

![image](https://user-images.githubusercontent.com/1628654/80112979-00918180-8582-11ea-8837-0265b9e654aa.png)

Folgendes ist dann im smartapplianceenabler.log zu finden:

`16:43:08.531 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
16:43:08.578 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
16:43:08.578 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
16:43:08.579 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.29]
16:43:10.662 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
16:43:10.663 [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 6424 ms
16:43:12.421 [main] INFO  o.h.validator.internal.util.Version - HV000001: Hibernate Validator 6.0.18.Final
16:43:13.583 [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
16:43:13.705 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
16:43:30.026 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:30.027 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:33.097 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:33.097 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:36.169 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:36.169 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:42.313 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:42.313 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:45.385 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:45.385 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:48.457 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:48.457 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:51.602 [http-nio-8080-exec-1] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring DispatcherServlet 'dispatcherServlet'
16:43:51.602 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcherServlet'
16:43:51.637 [http-nio-8080-exec-1] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 35 ms
16:43:54.601 [http-nio-8080-exec-1] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:54.601 [http-nio-8080-exec-1] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:54.602 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:54.602 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:57.677 [http-nio-8080-exec-1] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:57.677 [http-nio-8080-exec-1] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:57.678 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
16:43:57.678 [Timer-0] INFO  o.a.http.impl.execchain.RetryExec - Retrying request to {}->http://10.24.7.34:80
16:43:57.678 [http-nio-8080-exec-2] INFO  o.a.http.impl.execchain.RetryExec - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.24.7.34:80: No route to host (Host unreachable)
`

**Comment by camueller** [comment]
Das kann ich nicht bestätigen. Habe gerade die Gosund SP111 meiner Espresso-Maschine aus der Steckdose gezogen. Im Log tauchen die zu erwartenden Exceptions auf, aber die Status-Darstellung der anderen Geräte funktioniert einwandfrei.
Aus meiner Sicht ist das Verhalten so in Ordnung.

**Comment by reneschuster** [comment]
Hier ist es reproduzierbar mit folgendem im debug log:

`
2020-04-23 20:42:59,968 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000003780-00: Executing timer task name=PollPowerMeter id=1594189820
2020-04-23 20:42:59,969 DEBUG [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:105] F-24071977-000000003780-00: Sending GET request url=http://10.24.7.34/cm?cmnd=Status%208
2020-04-23 20:43:00,818 DEBUG [http-nio-8080-exec-45] d.a.s.w.SaeController [SaeController.java:772] Received request for ApplianceStatus
2020-04-23 20:43:00,818 DEBUG [http-nio-8080-exec-45] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:105] F-24071977-000000003780-00: Sending GET request url=http://10.24.7.34/cm?cmnd=Power
2020-04-23 20:43:04,973 ERROR [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:115] F-24071977-000000003780-00: Error executing GET request.
org.apache.http.conn.ConnectTimeoutException: Connect to 10.24.7.34:80 [/10.24.7.34] failed: connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.get(HttpTransactionExecutor.java:111)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.executeLeaveOpen(HttpTransactionExecutor.java:94)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.execute(HttpTransactionExecutor.java:74)
        at de.avanux.smartapplianceenabler.http.HttpHandler.getValue(HttpHandler.java:85)
        at de.avanux.smartapplianceenabler.http.HttpHandler.getFloatValue(HttpHandler.java:45)
        at de.avanux.smartapplianceenabler.meter.HttpElectricityMeter.getValue(HttpElectricityMeter.java:269)
        at de.avanux.smartapplianceenabler.meter.HttpElectricityMeter.pollPower(HttpElectricityMeter.java:247)
        at de.avanux.smartapplianceenabler.meter.PollPowerMeter.addValue(PollPowerMeter.java:70)
        at de.avanux.smartapplianceenabler.meter.PollPowerMeter$1.runTask(PollPowerMeter.java:54)
        at de.avanux.smartapplianceenabler.util.GuardedTimerTask.run(GuardedTimerTask.java:57)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 21 common frames omitted
2020-04-23 20:43:04,973 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:86] F-24071977-000000003780-00: url=http://10.24.7.34/cm?cmnd=Status%208 httpMethod=GET data=null path=null
2020-04-23 20:43:04,973 DEBUG [Timer-0] d.a.s.u.TimestampBasedCache [TimestampBasedCache.java:62] F-24071977-000000003780-00: cache=Power added value=0.0 timestamp=2020-04-23T20:42:59.969025  removed/total: 1/7
2020-04-23 20:43:04,973 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000003780-00: Executing timer task name=UpdateActiveTimeframeInterval id=1194637195
2020-04-23 20:43:04,973 DEBUG [Timer-0] d.a.s.s.TimeframeIntervalHandler [TimeframeIntervalHandler.java:135] F-24071977-000000003780-00: Current Queue:
2020-04-23 20:43:04,974 DEBUG [Timer-0] d.a.s.s.TimeframeIntervalHandler [TimeframeIntervalHandler.java:219] F-24071977-000000003780-00: QUEUED/2020-04-24T09:00:00/2020-04-24T18:00:00::ENABLED/0s/14400s
2020-04-23 20:43:04,974 DEBUG [Timer-0] d.a.s.s.TimeframeIntervalHandler [TimeframeIntervalHandler.java:219] F-24071977-000000003780-00: QUEUED/2020-04-25T09:00:00/2020-04-25T18:00:00::ENABLED/0s/14400s
2020-04-23 20:43:04,974 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000003780-00: Executing timer task name=PollEnergyMeter id=2048318048
2020-04-23 20:43:04,974 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000002002-00: Executing timer task name=PollEnergyMeter id=823439298
2020-04-23 20:43:05,821 ERROR [http-nio-8080-exec-45] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:115] F-24071977-000000003780-00: Error executing GET request.
org.apache.http.conn.ConnectTimeoutException: Connect to 10.24.7.34:80 [/10.24.7.34] failed: connect timed out
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.get(HttpTransactionExecutor.java:111)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.executeLeaveOpen(HttpTransactionExecutor.java:94)
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.execute(HttpTransactionExecutor.java:74)
        at de.avanux.smartapplianceenabler.http.HttpHandler.getValue(HttpHandler.java:85)
        at de.avanux.smartapplianceenabler.http.HttpHandler.getBooleanValue(HttpHandler.java:67)
        at de.avanux.smartapplianceenabler.control.HttpSwitch.isOn(HttpSwitch.java:118)
        at de.avanux.smartapplianceenabler.webservice.SaeController.getApplianceStatus(SaeController.java:793)
        at de.avanux.smartapplianceenabler.webservice.SaeController.getApplianceStatus(SaeController.java:763)
        at jdk.internal.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1591)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        ... 58 common frames omitted
2020-04-23 20:43:05,822 DEBUG [http-nio-8080-exec-45] d.a.s.h.HttpHandler [HttpHandler.java:86] F-24071977-000000003780-00: url=http://10.24.7.34/cm?cmnd=Power httpMethod=GET data=null path=null
2020-04-23 20:43:05,822 DEBUG [http-nio-8080-exec-45] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:105] F-24071977-000000003780-00: Sending GET request url=http://10.24.7.34/cm?cmnd=Power
`

Sogar der SHM bekommt es direkt nach dem ziehen des Schalters mit und kann nicht mehr mit dem SAE komminzieren bis ich den Schalter wieder einstecke:

![image](https://user-images.githubusercontent.com/1628654/80138165-b2da4080-85a4-11ea-82d4-ebb0ac8f6313.png)

**Comment by reneschuster** [comment]
Habe gerade rausgefunden, dass es nur mit dem Schalter auftritt, bei dem auch Unterbrechnung erlaubt ist. Bei den anderen 4 Tasmota Schalter tritt es nicht auf.

**Comment by reneschuster** [comment]
```
    <DeviceInfo>
        <Identification>
            <DeviceId>F-24071977-000000003780-00</DeviceId>
            <DeviceName>Lüfter</DeviceName>
            <DeviceType>Other</DeviceType>
            <DeviceSerial>STLFSC-42U-68-GSB</DeviceSerial>
            <DeviceVendor>START.LAN</DeviceVendor>
        </Identification>
        <Characteristics>
            <MaxPowerConsumption>65</MaxPowerConsumption>
        </Characteristics>
        <Capabilities>
            <CurrentPower>
                <Method>Measurement</Method>
            </CurrentPower>
            <Interruptions>
                <InterruptionsAllowed>true</InterruptionsAllowed>
            </Interruptions>
            <Requests>
                <OptionalEnergy>true</OptionalEnergy>
            </Requests>
        </Capabilities>
    </DeviceInfo>

```

```
    <Appliance id="F-24071977-000000003780-00">
        <HttpSwitch>
            <HttpWrite url="http://10.24.7.34/cm?cmnd=Power%20On">
                <HttpWriteValue name="On"/>
            </HttpWrite>
            <HttpWrite url="http://10.24.7.34/cm?cmnd=Power%20Off">
                <HttpWriteValue name="Off"/>
            </HttpWrite>
            <HttpRead url="http://10.24.7.34/cm?cmnd=Power">
                <HttpReadValue name="On" extractionRegex=":.ON"/>
            </HttpRead>
        </HttpSwitch>
        <HttpElectricityMeter>
            <HttpRead url="http://10.24.7.34/cm?cmnd=Status%208">
                <HttpReadValue name="Power" extractionRegex=",.Power.:(\d+)."/>
            </HttpRead>
        </HttpElectricityMeter>
        <Schedule enabled="true">
            <RuntimeRequest min="0" max="14400"/>
            <DayTimeframe>
                <Start hour="9" minute="0" second="0"/>
                <End hour="18" minute="0" second="0"/>
            </DayTimeframe>
        </Schedule>
    </Appliance>
```

**Comment by camueller** [comment]
Ich schaue mir das noch mal an ...

**Comment by camueller** [comment]
Ich habe jetzt mit Deinen Daten aus `Appliances.xml` (nur IP-Adresse geändert) und `Device2EM.xml` Dein Szenario nachgestellt, d.h. SAE gestartet und danach den *Gosund SP111* aus der Steckdose gezogen. Der SAE läuft weiter, aber loggt Fehler, weil er die *Gosund SP111* nicht erreichen kann.

Die Frage ist, welche Auswirkungen das auf die Abfrage durch den SHM hat. Also habe ich im Browser `http://raspi:8080/semp` aufgerufen. Hier dauert es jetzt in der Tat 12s, bis der SAE das XML liefert. Das könnte für den SHM u.U. zu lange sein, wobei diese Zeit für jedes Gerät anfällt, das nicht erreichbar ist, falls eingstellt ist, dass der Schalter-Status über HTTP abgefragt werden soll.

Im Http-Client setze ich 5s als Timeout für Connect, Request, Socket. Ich könnte diese Timeouts ändern, aber es wird das eigentliche Problem nicht lösen. Wenn der Schaltstatus von Geräten abgefragt werden soll, dann müssen diese auch erreichbar sein. Oder hast Du eine bessere Idee?

**Comment by reneschuster** [comment]
Ich bin auch nur auf dieses Problem gestoßen, da sich dieser Tasmota Schalter aufgehängt hatte und somit nicht mehr erreichbar war. Ansonsten stecken die immer in der Steckdose und das Problem tritt ja nicht auf. 

Bis jetzt fällt mir leider dazu auch nichts ein, wie man das lösen könnte.

**Comment by reneschuster** [comment]
Von den Gosund SP111 bin ich total enttäuscht. Habe 2 Stück davon und einer ist auch schon hinüber. Außerdem messen die total den Murks, obwohl ich jetzt nicht eine genaue Messung erwarten würde. Die macht extreme Sprünge und ein justieren der Messung hat auch keine Hilfe gebracht.

Anders sieht es mit den Gosund SP1 aus. Davon habe ich 4 Stück und die Messung ist viel besser und davon ist noch keiner kaput gegangen. Einen Sonoff POW2 habe ich auch und der läuft bisher auch stabil.

Vom SAE werden im Moment 3 x SP1 und 1 x SP111 gesteuert.

**Comment by premultiply** [comment]
Sehr interessante Infos zu der Qualität und Haltbarkeit der Geräte!
Bei der Pumpe (Hauswasserwerk?) ist vielleicht der Anlaufstrom so hoch dass die Relaiskontakte des dafür unterdimensionierten Relais abbrennen bzw. beim abschalten funken überschlagen.

Könnt ihr mir sagen welche der kompatiblen Mess- und Schalt-Zwischenstecker man mit der Originalsoftware auch nur lokal ohne jegliche Cloud und sonstigen Firlefanz betreiben kann?
Ich möchte gerne die Spül- und Waschmaschienen anbinden.

**Comment by camueller** [comment]
Soweit ich weiß, kann Shelly Plug S verwendet werden mit Original-Software.
https://www.photovoltaikforum.com/thread/104060-ger%C3%A4te-mit-home-manager-koppeln-via-semp-ethernet/?postID=1803644#post1803644

**Comment by camueller** [comment]
An der Wasserpumpe habe ich seit heute ein Sonoff Pow R2. Mal sehen, ob der dort länger hält, als die 5 Gosund SP111, die dort innerhalb eines halben Jahres kaputt gegangen sind.

**Comment by camueller** [comment]
> Ich habe jetzt mit Deinen Daten aus `Appliances.xml` (nur IP-Adresse geändert) und `Device2EM.xml` Dein Szenario nachgestellt, d.h. SAE gestartet und danach den _Gosund SP111_ aus der Steckdose gezogen. Der SAE läuft weiter, aber loggt Fehler, weil er die _Gosund SP111_ nicht erreichen kann.
> 
> Die Frage ist, welche Auswirkungen das auf die Abfrage durch den SHM hat. Also habe ich im Browser `http://raspi:8080/semp` aufgerufen. Hier dauert es jetzt in der Tat 12s, bis der SAE das XML liefert. Das könnte für den SHM u.U. zu lange sein, wobei diese Zeit für jedes Gerät anfällt, das nicht erreichbar ist, falls eingstellt ist, dass der Schalter-Status über HTTP abgefragt werden soll.
> 
> Im Http-Client setze ich 5s als Timeout für Connect, Request, Socket. Ich könnte diese Timeouts ändern, aber es wird das eigentliche Problem nicht lösen. Wenn der Schaltstatus von Geräten abgefragt werden soll, dann müssen diese auch erreichbar sein. Oder hast Du eine bessere Idee?

Für SAE 1.6.7 hatte ich die Retries entfernt, da ich die Fehler zähle und ggf. eine Benachrichtigung sende.
Dadurch entfällt auch die Verzögerung beim Aufruf von /semp, d.h. statt 12s Verzögerung nach dem Entfernen der SP111 aus der Steckdose kommt es aktuell zu keinen Verzögerungen dadurch.
