### ISSUE TITLE
SEMP funktioniert nicht mit VPN (wireguard) - default interface/IP range?

### ISSUE THREAD

**Issue by Schm1tz1** [camueller/SmartApplianceEnabler#168]
Vorab: Das Problem besteht mir aktueller Release und auch der neuen Beta. 

Mein Setup ist ein RPi3B mit openHAB und einem Wireguard-VPN-Interface. Ich habe mich länger gewundert, warum Geräte im SunnyPortal nicht gefunden werden - erster Hinweis im Log:

> 08:59:12.720 [cling-5] ERROR o.f.cling.transport.spi.DatagramIO - Exception sending datagram to: /239.255.255.250: java.io.IOException: Der notwendige Schlüssel ist nicht verfügbar
> java.io.IOException: Der notwendige Schlüssel ist nicht verfügbar
>         at java.base/java.net.PlainDatagramSocketImpl.send(Native Method)
>         at java.base/java.net.DatagramSocket.send(DatagramSocket.java:695)
>         at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:159)
>         at org.fourthline.cling.transport.impl.DatagramIOImpl.send(DatagramIOImpl.java:150)
>         at org.fourthline.cling.transport.RouterImpl.send(RouterImpl.java:309)
>         at org.fourthline.cling.protocol.async.SendingNotification.sendMessages(SendingNotification.java:110)
>         at org.fourthline.cling.protocol.async.SendingNotification.execute(SendingNotification.java:84)
>         at org.fourthline.cling.protocol.async.SendingNotificationAlive.execute(SendingNotificationAlive.java:41)
>         at org.fourthline.cling.protocol.SendingAsync.run(SendingAsync.java:54)
>         at org.fourthline.cling.registry.LocalItems$4.run(LocalItems.java:298)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> (END)

Problem hängt offensichtlich mit dem SEMP-Discoery/Broacast auf einer nicht unterstützten Schnittstelle zusammen. Testweise wurden alle Interfaces ausser eth0 aktiviert, dann SAE neugestartet -> läuft.

Das Rolling Log zeigt:

> INFO [main] d.a.s.s.d.SempDiscovery [SempDiscovery.java:58] SEMP UPnP will redirect to http://10.9.8.33:9090

Anscheinend wird hier das falsche default-Interface verwendet für das Discovery, denn das ist der IP-Range für mein internes über Wireguard verbundenes Netz. 

Frage: Gibt es eine Möglichkeit, einen IP-Range oder ein Interface für SEMP zu setzen, ggf. über eine property? Ich kenne leider cling (noch) nicht, sonst hätte ich schon an einem Fork dafür gearbeitet.

**Comment by Schm1tz1** [comment]
Teil 1 des Problems ist gelöst - sinnigerweise die **server.address** in _/etc/default/smartapplianceenabler_ auf die lokale IP im Netz setzen:

```
# Enable this line to bind the Smart Appliance Enabler to a specific network address.
# This has to be the address of one of the local network interfaces.
JAVA_OPTS="${JAVA_OPTS} -Dserver.address=192.168.178.33"
```

Leider wird das Gerät trotz Überprüfung SEMP1, SP1 nicht gefunden. Alle Geräte sind aktiv, SEMP-URL funktioniert, man sieht das Discovery in Log, aber auch nach 20 Minuten kein Eintrag in SunnyPortal.

**Comment by Schm1tz1** [comment]
Problem gelöst, kein Issue mit dem SAE, sorry. Es liegt im SHM/SunnyPortal. Zuvor gelöschte Geräte werden nicht neu gefunden, sondern müssen manuell hinzugefügt werden.
