### ISSUE TITLE
Anlaufstromerkennung funktioniert nach Verbindungsfehler nicht mehr

### ISSUE THREAD

**Issue by bunnu** [camueller/SmartApplianceEnabler#29]
Nach 1 - 3 Tagen erkennt SmartApplianceEnabler den Anlaufstrom nicht mehr. Ich habe nun ins Log geschaut und gesehen, dass es Fehler bei der Abfrage des aktuellen Verbrauchs gab. Folgende Fehlermeldung erscheint drei mal im Abstand von 30 Sekunden. Danach endet das Log:

```
2017-12-13 09:48:04,720 ERROR [Timer-0] d.a.s.h.HttpTransactionExecutor [ApplianceLogger.java:209] F-20130830-000000000002-00: Error executing HTTP request.
java.net.NoRouteToHostException: Keine Route zum Zielrechner (Host unreachable)
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_151]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_151]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_151]
        at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[httpclient-4.5.1.jar!/:4.5.1]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107) ~[httpclient-4.5.1.jar!/:4.5.1]
        at de.avanux.smartapplianceenabler.http.HttpTransactionExecutor.sendHttpRequest(HttpTransactionExecutor.java:115) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.meter.HttpElectricityMeter.getPower(HttpElectricityMeter.java:122) [classes!/:na]
        at de.avanux.smartapplianceenabler.meter.PollElectricityMeter$1.run(PollElectricityMeter.java:45) [classes!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_151]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_151]
```

SAE läuft weiterhin. Allerdings funktioniert die Anlaufstromerkennung erst dann wieder, wenn ich den Dienst neu starte.

**Comment by camueller** [comment]
Die Fehlermeldung hat nichts mit dem SAE selbst zu tun, sondern mit Netzwerkproblemen oder einem falsch angegebenen Hostnamen / IP-Adresse.

**Comment by bunnu** [comment]
Hostname / IP-Adresse ist korrekt. Die Anlaufstromerkennung funktioniert prinzipiell auch. Warum auch immer, gibt es hin und wieder Verbindungsprobleme zur Edimax-Steckdose. Ich finde SAE sollte bei Verbindungsproblemen weiterhin pollen und nicht nach drei Versuchen aufhören.
