### ISSUE TITLE
Bug Http-Schalter Status abfrage in Kombination mit Anlaufstromerkennung

### ISSUE THREAD

**Issue by reneschuster** [camueller/SmartApplianceEnabler#70]
Der Test erfolge mit SAE 1.4.17 auf einem Debian Buster LXC Container mit Oracle Java 1.8.0_65.

Die Statusabfrage mit einem Gosund SP1 funktioniert solange keine Anlaufstromerkennung aktiviert wird. Beim Aktivieren der Anlaufstromerkennung wird folgender Fehler geworfen:

```
2019-11-10 15:36:14,420 DEBUG [http-nio-8080-exec-7] d.a.s.w.GensonHttpMessageConverter [GensonHttpMessageConverter.java:79] Deserializing JSON to interface de.avanux.smartapplianceenabler.control.Control
2019-11-10 15:36:14,423 DEBUG [http-nio-8080-exec-7] d.a.s.w.SaeController [SaeController.java:283] F-24071977-000000001234-00: Received request to set control de.avanux.smartapplianceenabler.control.StartingCurrentSwitch@3d706b42
2019-11-10 15:36:14,423 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:370] F-24071977-000000001234-00: Set control
2019-11-10 15:36:14,424 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:213] Saving to file: writeDevice2EM=false writeAppliances=true
2019-11-10 15:36:14,462 DEBUG [http-nio-8080-exec-7] d.a.s.u.FileHandler [FileHandler.java:107] File /opt/sae/Appliances.xml written
2019-11-10 15:36:14,463 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:127] Restarting ...
2019-11-10 15:36:14,463 INFO [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:131] F-24071977-000000001234-00: Stopping appliance ...
2019-11-10 15:36:14,464 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:296] F-24071977-000000001234-00: Stopping appliance ...
2019-11-10 15:36:14,464 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:300] F-24071977-000000001234-00: Stopping StartingCurrentSwitch
2019-11-10 15:36:14,465 DEBUG [http-nio-8080-exec-7] d.a.s.c.StartingCurrentSwitch [StartingCurrentSwitch.java:172] F-24071977-000000001234-00: Stopping ...
2019-11-10 15:36:14,465 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:305] F-24071977-000000001234-00: Stopping meter HttpElectricityMeter
2019-11-10 15:36:14,466 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:206] F-24071977-000000001234-00: Stopping ...
2019-11-10 15:36:14,467 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:66] F-24071977-000000001234-00: Cancel timer task name=PollEnergyMeter id=653147066
2019-11-10 15:36:14,467 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:66] F-24071977-000000001234-00: Cancel timer task name=PollPowerMeter id=1544918117
2019-11-10 15:36:14,468 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:310] F-24071977-000000001234-00: Cancel runningTimeMonitor timer
2019-11-10 15:36:14,468 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:66] F-24071977-000000001234-00: Cancel timer task name=UpdateActiveTimeframeInterval id=1478955579
2019-11-10 15:36:14,469 INFO [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:136] Restarting appliances ...
2019-11-10 15:36:14,469 INFO [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:96] Starting appliances ...
2019-11-10 15:36:14,470 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:98] Loading Appliances.xml ...
2019-11-10 15:36:14,524 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:162] null Set acceptControlRecommendations=true
2019-11-10 15:36:14,542 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:106] Loading Appliances.xml ...
2019-11-10 15:36:14,577 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:143] Initializing ...
2019-11-10 15:36:14,590 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:167] F-24071977-000000001234-00: Initializing appliance ...
2019-11-10 15:36:14,590 WARN [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:81] GPIO access disabled - not running on Raspberry Pi.
2019-11-10 15:36:14,592 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:184] F-24071977-000000001234-00: Initializing appliance
2019-11-10 15:36:14,593 DEBUG [http-nio-8080-exec-7] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:53] F-24071977-000000001234-00: Initialize state
2019-11-10 15:36:14,593 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:197] F-24071977-000000001234-00: Registered as ControlStateChangedListener with StartingCurrentSwitch
2019-11-10 15:36:14,593 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:200] F-24071977-000000001234-00: Registered as StartingCurrentSwitchListener with StartingCurrentSwitch
2019-11-10 15:36:14,594 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:224] F-24071977-000000001234-00: HttpElectricityMeter uses StartingCurrentSwitch
2019-11-10 15:36:14,594 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:230] F-24071977-000000001234-00: StartingCurrentSwitch uses HttpElectricityMeter
2019-11-10 15:36:14,595 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:253] F-24071977-000000001234-00: Schedules configured: 1
2019-11-10 15:36:14,595 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:169] F-24071977-000000001234-00: Validating appliance ...
2019-11-10 15:36:14,596 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:265] F-24071977-000000001234-00: Validating appliance configuration
2019-11-10 15:36:14,596 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:115] F-24071977-000000001234-00: Validating configuration
2019-11-10 15:36:14,597 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:116] F-24071977-000000001234-00: configured: poll interval=10s / measurement interval=60s
2019-11-10 15:36:14,597 DEBUG [http-nio-8080-exec-7] d.a.s.h.HttpValidator [HttpValidator.java:42] F-24071977-000000001234-00: Power configured: read url=http://10.24.7.19/cm?cmnd=Status%208 data=null path=null extractionRegex=,.Power.:(\d+). factorToValue=null
2019-11-10 15:36:14,598 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:171] F-24071977-000000001234-00: Starting appliance ...
2019-11-10 15:36:14,598 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:275] F-24071977-000000001234-00: Starting appliance
2019-11-10 15:36:14,599 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] F-24071977-000000001234-00: Created timer task name=UpdateActiveTimeframeInterval period=30000ms id=1741585575
2019-11-10 15:36:14,599 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000001234-00: Executing timer task name=UpdateActiveTimeframeInterval id=1741585575
2019-11-10 15:36:14,599 DEBUG [Timer-0] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:247] F-24071977-000000001234-00: Timeframe interval activation check: notifying ActiveIntervalChangedListener Appliance
2019-11-10 15:36:14,600 DEBUG [Timer-0] d.a.s.a.Appliance [Appliance.java:982] F-24071977-000000001234-00: Checking running time: remainingMinRunningTime=null remainingMaxRunningTime=null
2019-11-10 15:36:14,600 DEBUG [Timer-0] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:214] F-24071977-000000001234-00: activeTimeframeInterval=null
2019-11-10 15:36:14,600 DEBUG [Timer-0] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:215] F-24071977-000000001234-00: runningTime=null remainingMinRunningTime=null remainingMaxRunningTime=null
2019-11-10 15:36:14,600 DEBUG [Timer-0] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:218] F-24071977-000000001234-00: running=false interrupted=false statusChangedAt=null
2019-11-10 15:36:14,600 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:283] F-24071977-000000001234-00: Starting HttpElectricityMeter
2019-11-10 15:36:14,601 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:199] F-24071977-000000001234-00: Starting ...
2019-11-10 15:36:14,601 DEBUG [http-nio-8080-exec-7] d.a.s.u.TimestampBasedCache [TimestampBasedCache.java:40] F-24071977-000000001234-00: maxAgeSeconds=60
2019-11-10 15:36:14,602 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] F-24071977-000000001234-00: Created timer task name=PollEnergyMeter period=10000ms id=114692499
2019-11-10 15:36:14,602 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000001234-00: Executing timer task name=PollEnergyMeter id=114692499
2019-11-10 15:36:14,603 DEBUG [http-nio-8080-exec-7] d.a.s.u.TimestampBasedCache [TimestampBasedCache.java:40] F-24071977-000000001234-00: maxAgeSeconds=60
2019-11-10 15:36:14,603 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] F-24071977-000000001234-00: Created timer task name=PollPowerMeter period=10000ms id=443789035
2019-11-10 15:36:14,604 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000001234-00: Executing timer task name=PollPowerMeter id=443789035
2019-11-10 15:36:14,604 DEBUG [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:105] F-24071977-000000001234-00: Sending GET request url=http://10.24.7.19/cm?cmnd=Status%208
2019-11-10 15:36:14,622 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:288] F-24071977-000000001234-00: Starting StartingCurrentSwitch
2019-11-10 15:36:14,622 INFO [http-nio-8080-exec-7] d.a.s.c.StartingCurrentSwitch [StartingCurrentSwitch.java:142] F-24071977-000000001234-00: Starting current switch: powerThreshold=15W startingCurrentDetectionDuration=30s finishedCurrentDetectionDuration=300s minRunningTime=600s
2019-11-10 15:36:14,623 DEBUG [http-nio-8080-exec-7] d.a.s.c.StartingCurrentSwitch [StartingCurrentSwitch.java:202] F-24071977-000000001234-00: Setting wrapped appliance switch to on
2019-11-10 15:36:14,623 INFO [http-nio-8080-exec-7] d.a.s.c.HttpSwitch [HttpSwitch.java:128] F-24071977-000000001234-00: Switching on
2019-11-10 15:36:14,624 DEBUG [http-nio-8080-exec-7] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:105] F-24071977-000000001234-00: Sending GET request url=http://10.24.7.19/cm?cmnd=Power%20On
2019-11-10 15:36:14,749 DEBUG [Timer-0] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:160] F-24071977-000000001234-00: Response code is 200
2019-11-10 15:36:14,752 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:86] F-24071977-000000001234-00: url=http://10.24.7.19/cm?cmnd=Status%208 httpMethod=GET data=null path=null
2019-11-10 15:36:14,752 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:89] F-24071977-000000001234-00: Response: {"StatusSNS":{"Time":"2019-11-10T15:36:13","ENERGY":{"TotalStartTime":"2019-10-20T13:45:00","Total":0.014,"Yesterday":0.000,"Today":0.002,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
2019-11-10 15:36:14,752 DEBUG [Timer-0] d.a.s.h.HttpHandler [HttpHandler.java:58] F-24071977-000000001234-00: value=0.0 protocolHandlerValue={"StatusSNS":{"Time":"2019-11-10T15:36:13","ENERGY":{"TotalStartTime":"2019-10-20T13:45:00","Total":0.014,"Yesterday":0.000,"Today":0.002,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}} valueExtractionRegex=,.Power.:(\d+). extractedValue=0
2019-11-10 15:36:14,753 DEBUG [Timer-0] d.a.s.u.TimestampBasedCache [TimestampBasedCache.java:62] F-24071977-000000001234-00: cache=Power added value=0.0 timestamp=1573396574604  removed/total: 0/1
2019-11-10 15:36:14,799 DEBUG [http-nio-8080-exec-7] d.a.s.h.HttpTransactionExecutor [HttpTransactionExecutor.java:160] F-24071977-000000001234-00: Response code is 200
2019-11-10 15:36:14,799 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] F-24071977-000000001234-00: Created timer task name=DetectStartingCurrent period=30000ms id=338404729
2019-11-10 15:36:14,799 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000001234-00: Executing timer task name=DetectStartingCurrent id=338404729
2019-11-10 15:36:14,800 ERROR [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:60] F-24071977-000000001234-00: Error executing timer task name=DetectStartingCurrent id=338404729
java.lang.NullPointerException: null
        at de.avanux.smartapplianceenabler.http.HttpHandler.getValue(HttpHandler.java:85) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.http.HttpHandler.getBooleanValue(HttpHandler.java:67) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.HttpSwitch.isOn(HttpSwitch.java:119) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch.isApplianceOn(StartingCurrentSwitch.java:213) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch.detectStartingCurrent(StartingCurrentSwitch.java:225) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch$1.runTask(StartingCurrentSwitch.java:155) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.util.GuardedTimerTask.run(GuardedTimerTask.java:57) ~[classes!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_65]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_65]
2019-11-10 15:36:14,800 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] F-24071977-000000001234-00: Created timer task name=DetectFinishedCurrent period=300000ms id=575108326
2019-11-10 15:36:14,801 INFO [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:290] F-24071977-000000001234-00: Switch off appliance initially
2019-11-10 15:36:14,801 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] F-24071977-000000001234-00: Executing timer task name=DetectFinishedCurrent id=575108326
2019-11-10 15:36:14,801 ERROR [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:60] F-24071977-000000001234-00: Error executing timer task name=DetectFinishedCurrent id=575108326
java.lang.NullPointerException: null
        at de.avanux.smartapplianceenabler.http.HttpHandler.getValue(HttpHandler.java:85) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.http.HttpHandler.getBooleanValue(HttpHandler.java:67) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.HttpSwitch.isOn(HttpSwitch.java:119) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch.isApplianceOn(StartingCurrentSwitch.java:213) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch.detectFinishedCurrent(StartingCurrentSwitch.java:265) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.control.StartingCurrentSwitch$2.runTask(StartingCurrentSwitch.java:163) ~[classes!/:na]
        at de.avanux.smartapplianceenabler.util.GuardedTimerTask.run(GuardedTimerTask.java:57) ~[classes!/:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_65]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_65]
2019-11-10 15:36:14,802 DEBUG [http-nio-8080-exec-7] d.a.s.c.StartingCurrentSwitch [StartingCurrentSwitch.java:186] F-24071977-000000001234-00: Setting appliance switch to off
2019-11-10 15:36:14,802 DEBUG [http-nio-8080-exec-7] d.a.s.c.StartingCurrentSwitch [StartingCurrentSwitch.java:194] F-24071977-000000001234-00: Notifying ControlStateChangedListener Appliance
2019-11-10 15:36:14,802 DEBUG [http-nio-8080-exec-7] d.a.s.a.Appliance [Appliance.java:895] F-24071977-000000001234-00: Control state has changed to off
2019-11-10 15:36:14,803 DEBUG [http-nio-8080-exec-7] d.a.s.a.RunningTimeMonitor [RunningTimeMonitor.java:139] F-24071977-000000001234-00: Set running=false statusChangedAt=2019-11-10T15:36:14.598
2019-11-10 15:36:14,803 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:169] F-24071977-000000001234-00: Stop energy meter ...
2019-11-10 15:36:14,804 DEBUG [http-nio-8080-exec-7] d.a.s.m.HttpElectricityMeter [HttpElectricityMeter.java:171] F-24071977-000000001234-00: Current energy meter value: 0.0 kWh
2019-11-10 15:36:14,804 DEBUG [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:176] Holidays are used.
2019-11-10 15:36:14,804 DEBUG [http-nio-8080-exec-7] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:40] : Created timer task name=HolidaysDownloader period=86400000ms id=633635507
2019-11-10 15:36:14,805 INFO [http-nio-8080-exec-7] d.a.s.a.ApplianceManager [ApplianceManager.java:123] 1 appliance(s) configured.
2019-11-10 15:36:14,805 DEBUG [Timer-0] d.a.s.u.GuardedTimerTask [GuardedTimerTask.java:54] : Executing timer task name=HolidaysDownloader id=633635507
2019-11-10 15:36:14,805 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:137] Using holidays file /opt/sae/Holidays-2019.txt
2019-11-10 15:36:14,806 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-10-03
2019-11-10 15:36:14,806 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-04-19
2019-11-10 15:36:14,806 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-06-10
2019-11-10 15:36:14,807 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-05-30
2019-11-10 15:36:14,807 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-12-26
2019-11-10 15:36:14,807 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-12-25
2019-11-10 15:36:14,808 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-01-01
2019-11-10 15:36:14,808 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-04-22
2019-11-10 15:36:14,808 DEBUG [Timer-0] d.a.s.u.FileHandler [FileHandler.java:145] Loaded holiday: 2019-05-01
2019-11-10 15:36:14,825 DEBUG [http-nio-8080-exec-9] d.a.s.w.SaeController [SaeController.java:166] Received request for ApplianceHeaders
2019-11-10 15:36:14,825 DEBUG [http-nio-8080-exec-9] d.a.s.w.SaeController [SaeController.java:176] Returning 1 ApplianceHeaders
2019-11-10 15:36:14,826 DEBUG [http-nio-8080-exec-9] d.a.s.w.GensonHttpMessageConverter [GensonHttpMessageConverter.java:86] Serializing class java.util.ArrayList to JSON
```

**Comment by camueller** [comment]
Den Fehler habe ich gestern bei mir selbst entdeckt und behoben für die nächste Version.
